#!/usr/bin/env bash

set -e
cd '/home/ubuntu/app' || exit

docker-compose -f docker-compose-prod.yml ps
docker-compose -f docker-compose-prod.yml up -d --remove-orphans
docker-compose -f docker-compose-prod.yml ps
